on:
  push:
    branches:
      - 'main'
      
jobs:
  Generate-Changeloge:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
